// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  button: dynamic(() => import("./Button")),
  card: dynamic(() => import("./Card")),
  card_page: dynamic(() => import("./CardPage")),
  hero: dynamic(() => import("./Hero")),
  product_card: dynamic(() => import("./ProductCard")),
  slice_test: dynamic(() => import("./SliceTest")),
};
