"use client"

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyHeader from "../../components/Header/Header";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  useGSAP(() => {
    const tl = gsap.timeline()
    tl
      .from(".welcoming", {
        left: '-100vw',
        delay: 0
      })
      .from(".welcoming .welcome", {
        x: 500,
        opacity: 0
      })
      .from(".welcoming .to-my", {
        x: -500,
        opacity: 0
      })
      .from(".welcoming .personal", {
        x: 500,
        opacity: 0
      })
      .from(".welcoming .portfolio", {
        x: -500,
        opacity: 0
      })
      .to(".welcoming p", {
        opacity: 0,
        stagger: 0.3,
      }, '+=2')
      .to(".welcoming ", {
        left: '100vw',
        display: "none"
      })
      .to(".overlay span", {
        height: 0,
        stagger: 0.2
      })
      .to(".overlay", {
        display: "none"
      })
  }, [])

  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <MyHeader />
        {children}
      </body>
    </html>
  );
}
